### PR TITLE
Losslessly Optimize Images (Save 2.1MB in Repo)

### PR DESCRIPTION
**Pull request by Sewer56**

### CODE REVIEW

**Comment by xdevs23** [comment]
Are you sure that it is lossless? How did you do that?

**Comment by Sewer56** [comment]
Yeah :^). See Telegram.

**Comment by xdevs23** [comment]
Idk if I should do that. Test the theme and see if it works correctly.

**Comment by xdevs23** [comment]
I can cherry pick wanted changes tho.

**Comment by Sewer56** [comment]
I should have left this earlier: closed to superseed new PR of separate branch.

**Pull request closed without merging**
